services:
  db:
    image: postgres:16-alpine
    container_name: lab4-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: caruser
      POSTGRES_PASSWORD: carpass
      POSTGRES_DB: cardb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-internal

  crud-service:
    build: ./crud_service
    container_name: lab4-crud
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://caruser:carpass@db:5432/cardb
      REPORT_SERVICE_URL: http://report-service:8001
    ports:
      - "8000:8000"
    depends_on:
      - db
      - report-service
    networks:
      - db-internal
      - services-internal
      - default

  report-service:
    build: ./report_service
    container_name: lab4-report
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://caruser:carpass@db:5432/cardb
    depends_on:
      - db
    networks:
      - db-internal
      - services-internal

networks:
  db-internal:
    internal: true
  services-internal:
    internal: true

volumes:
  pgdata:
